import FinancialEntries from "./FinancialEntries"

export default function FinancialEntry(props){

    const entryType = props.entryType
    const onRowSelection = props.onRowSelection

    const products = [{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    },{
      "credit_card_desc": null,
      "credit_card_number": null,
      "description": "string",
      "entry_type_id": 0,
      "entry_type_name": "string",
      "financial_entry_category_id": 0,
      "financial_entry_category_name": "string",
      "finish_date": null,
      "id": 0,
      "name": "string",
      "recurrent": 0,
      "recurrent_desc": "string",
      "start_date": "2025-06-20",
      "value": null,
      "value_type_id": 0,
      "value_type_name": "string"
    }]

    return (
        <FinancialEntries financialEntryList={products} entryType={entryType} />
    )


}    